---
AWSTemplateFormatVersion: '2010-09-09'

Resources:
  # create random bucket
  myBucketResource:
    Type: AWS::S3::Bucket

  # create resource
  # this will be called when DELETE is initiated
  LambdaUsedToCleanUp:
    Type: Custom::cleanupbucketresource
    Properties:
      # this token here is ARN to custom lambda function that we created earlier
      ServiceToken: !ImportValue EmptyS3BucketLambda
      BucketName: !Ref myBucketResource
